version: '3'
services:
  dot-test:
    image: ramdanariadi/dot-test
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: postgres
      DB_PASS: p4ssw0rd
      DB_NAME: grocery
      DB_HOST: db
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - dot-network
    links:
      - cache
      - db
  cache:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - dot-network
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: grocery
      PGDATA: /var/lib/postgresql/data/grocery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/grocery
    networks:
      - dot-network
networks:
  dot-network:
    driver: bridge

volumes:
  pgdata:
    driver: "local"
  cache:
    driver: "local"